name = "Tools"
uuid = "1b08a953-4be3-4667-9a23-3db579824955"  # Random UUID
authors = ["Simone D'Ambrogio <simonedambrogio67@gmail.com>"]
version = "0.1.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1.11.3"
